# Generated by Django 5.0 on 2023-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('sent_email', 'sent_email'), ('verify_code', 'verify_code'), ('complate', 'complate')], default='sent_email', max_length=15),
        ),
    ]
